### ISSUE TITLE
Jira feature collector - about the Story.st file

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#225] opened 2015-12-16 03:38 UTC
story(changeDate) ::= "search?jql=updatedDate%3E%3D%27$changeDate$%27+AND+issueType%3D%277%27+ORDER+BY+updated"

what is the significance of 7 for issueType... --> issueType%3D%277 - it never works... when we change 7 to Story - it works but we suspect its not getting all the data..

What are the possible other values 1,2,3,4,5,6,7??? and what is the significance... why are we using 7 for story.st?

**Comment by amp5208** [comment] 2015-12-16 16:10
Thank you for reaching out regarding the Jira feature collector.  The “7” issueType signifies a “story” type issue in Jira.  This should be limiting results only to stories.  Sample valid query for demonstrative purposes:  https://jira.com/rest/api/2/search?jql=updatedDate%3E%3D%272015-12-1%27+AND+issueType%3D%277%27+ORDER+BY+updated

The following are API descriptions for issue types 1-9:

 - https://jira.com/rest/api/2/issuetype/1
 - https://jira.com/rest/api/2/issuetype/2
 - https://jira.com/rest/api/2/issuetype/3
 - https://jira.com/rest/api/2/issuetype/4
 - https://jira.com/rest/api/2/issuetype/5
 - https://jira.com/rest/api/2/issuetype/6
 - https://jira.com/rest/api/2/issuetype/7
 - https://jira.com/rest/api/2/issuetype/8
 - https://jira.com/rest/api/2/issuetype/9

Please let me know if you have any additional questions

**Comment by softwareklinic** [comment] 2015-12-16 22:45
Looks like these urls are obsolete... is there any on the new atlassian site?

**Comment by amp5208** [comment] 2015-12-17 16:23
Allow me to clarify:  You need to replace the "jira.com" host name part of those URLs with <em>your</em> fully qualified Jira host name.  I have edited the comment above to reflect this.

**Comment by amp5208** [comment] 2016-01-05 23:08
This issue will be fixed in the newest pull request regarding Feature Widget updates, as you will now be able to specify your Jira instance's custom "user story" issue type ID at deploy-time via properties file

**Comment by amp5208** [comment] 2016-01-15 19:26
@softwareklinic, this issue has now been resolved, as of the most recent update to master.  Please pull the newest code and evaluate.  Be sure to also update the following 3 property settings based on your Jira instance's configuration:

<pre>
. . .
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a numerical ID reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType ID
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
feature.jiraIssueTypeId=7
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10007
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10400
. . .
</pre>

**Comment by tabladrum** [comment] 2016-03-18 22:02
Closing it. If the issue is seen again, please reopen it.

**Closed by tabladrum** 2016-03-18 22:02 UTC
