### ISSUE TITLE
Install SSl certificate to get response from service in monitor widget

### ISSUE THREAD

**Issue by ameetsvshah** [capitalone/Hygieia#1689] opened 2017-08-30 13:51 UTC
We want to get response of HTTPS api URLs from monitor widget.
We need to install ssl certificates for this.
How can we enable SSL in Hygieia in monitor widget.

**Comment by nitin1706** [comment] 2017-09-28 20:25
Duplicate of #1702. Closing this issue here.

**Closed by nitin1706** 2017-09-28 20:25 UTC
