### ISSUE TITLE
Audit service improvements

### ISSUE THREAD

**Issue by mspiegel** [capitalone/Hygieia#1735] opened 2017-09-22 14:39 UTC
I think there are some improvements that can be made to the audit service. It looks like the service scans through the pull request comments and the pull request review comments. If any comments are present (and not by the PR author) then the pull request is considered reviewed.

See https://github.com/capitalone/Hygieia/blob/200f9154a9956283eb16ce01b4c5aa16b43b4d5a/api-audit/src/main/java/com/capitalone/dashboard/service/AuditServiceImpl.java#L290-L311

There are a couple of improvements that can be made:

A pull request review has a state. I see the states "PENDING", "APPROVED", "DISMISSED". There should also be a "Request Changes" status but I don't know is the corresponding API state. I think the service should be checking the state of the pull request review instead of looking at the review comments. The current implementation will accept "Pending" or "Request Changes" pull request reviews. That seems wrong. Here's the GitHub API: https://developer.github.com/v3/pulls/reviews/#get-a-single-review

There are external services that provide approval management. For example, Hygieia uses https://github.com/lgtmco/lgtm. It would be useful to allow a repository to configure Hygieia to recognize these services for approval management. These services work by setting a git commit status. The repository could register the status context with Hygieia, such as "approvals/lgtm" and that status check could be tested. https://developer.github.com/v3/repos/statuses/#list-statuses-for-a-specific-ref

Currently the audit service tests for the presence of any pull request comments. This doesn't seem like the correct behavior. For example, I could make a comment "Don't merge this. There's a NullPointerException on line 10" and that would be considered as peer review. I would remove the testing of pull request comments. Another option is to reproduce the functionality of a service like https://github.com/lgtmco/lgtm. It's a non-trivial implementation to reproduce that functionality.

I'm happy to submit pull requests on any of the three comments above. Just wanted to get feedback before I start writing code.

**Comment by tabladrum** [comment] 2017-09-22 15:11
Great feedback. Agree with (a) checking PR state. 
(b) We discussed the option of checking status of approval management hook. The problem is doing so is that those hooks can be turned off by a repo owner and turned back on after some direct commits to the branch by-passing PR mechanism and we won't know about it. There is a solution but may be a little overkill - we will need to trap into GH event stream. (c) We discussed this too. From a review comment perspective, a text saying "LGTM" is as good as "I am merging it anyway". IMO the correct way to do this would be to use some light weight sentiment analysis on the review comments and that itself will open up a good set of analytics points. 

Thoughts?

**Comment by mspiegel** [comment] 2017-09-22 15:57
On (b) I think only the repository administrators can enable or disable a service hook. I think you have to trust the repository admins. For example, the admins are the ones who can enable or disable a protected branch in GitHub. They are also the ones who decide whether or not admins can commit directly to a protected branch. So I think they have the equivalent or superuser or root access to the repository.

On (c) looking for the comment string "LGTM" would be an improvement over the current implementation. Sentiment analysis seems overkill IMO.

**Comment by mspiegel** [comment] 2017-09-22 15:59
The admins can also rewrite history on a protected branch, if they allow admins to commit directly to the branch.

**Comment by jdamick** [comment] 2017-09-25 14:45
yeah i would say you need to have trust at some level, so i would vote for (b) rather than (c) which would likely be a never ending stream of keyword matching or sentiment analysis..

**Comment by tabladrum** [comment] 2017-09-25 15:00
We should be able to support any code review process - LGTM, GH's own or anything else.

**Comment by mspiegel** [comment] 2017-10-04 02:46
Is there consensus on taking this course of action?
- use the GitHub API to check the GitHub Pull Request Review status?
- use the GitHub API to check the GitHub status checks for LGTM? 

I can submit a patch with these changes once we have consensus on what it needs to look like. Currently on master if someone types a comment "This pull request has a bug please don't merge it" the AuditStatus.PULLREQ_REVIEWED_BY_PEER status is set.

**Comment by tabladrum** [comment] 2017-10-04 13:43
Are we expecting this to work only with LGTM -i.e. detecting LGTM webhook etc? Or are we saying we will look for the word "LGTM" in the review comment? If it is the second one, I am concerned about this review comment "This pull request does not LGTM".

**Comment by poemdexter** [comment] 2017-10-04 17:42
I've received confirmation from several people that the LGTM tool is not required for SOD or PAR so we shouldn't rely on it too heavily.  The github API should be checked for review status and then maybe rely on LGTM comments afterwards.  Also LGTM can be turned off just as easily as protected branches in Github.

**Comment by poemdexter** [comment] 2017-10-04 17:46
Another thing to think about is the fact that many teams rely on the maven release plugin to handle versioning.  Every release creates 2 additional commits directly on the release branch changing the pom versioning.

**Comment by tabladrum** [comment] 2017-10-04 17:49
Those commits are marked as such so that they are excluded (need to confirm @satishc1 about the exclusions) from this.

**Comment by poemdexter** [comment] 2017-10-04 17:55
I've come across another team as well that creates commits as part of their release due to the fact that maven release plugin requires git to show no outstanding changes.  So this would be ignoring commits directly to release due to some build step as well as maven release plugin.

Overall, I feel like Github can easily be configured to control peer reviews and it's strange to see devs have full admin access to repos they commit to as part of a larger team.

**Comment by tabladrum** [comment] 2017-10-04 17:58
Send me (via offline) an example of such commit.

**Comment by mspiegel** [comment] 2017-10-04 18:09
There are two approaches to enforcing peer review. The first is to use the GitHub Pull Request Review feature and to check the box on the protected branch that requires a PR Review. The second is to use an external service such as the LGTM service and use a GitHub status check. Both approaches are valid. Using an external service can provide additional features that are not (currently) available in the GitHub Pull Request Review. For example, if you want to mandate a specific set of people to be reviewers. Or you want to require two or more reviewers for your pull request. Or you want to require that the author of the pull request is in the group of people who have signed a contributor license agreement.

What I'm requesting is that Hygieia support both of these approaches. I haven't had a second person confirm this, but it looks like the current implementation in Hygieia is broken? It just looks for the presence of comments. It doesn't test the GitHub Review API to check that the review was approved.

None of these these approaches address the issue of a malicious actor. The current implementation in Hygieia also doesn't address this question. I've been investigating some alternatives to solve that problem. Is that not a separate issue to be addressed? Can we first improve the current Hygieia peer review service?

**Comment by mspiegel** [comment] 2017-10-04 18:11
I'm working on some improvements to audit an external service such as LGTM. Let's talk about them in a less public venue.

**Comment by tabladrum** [comment] 2017-10-04 18:13
We are just starting to build this... it is not solid yet - not sure what broken means if it is not solid :-)

**Comment by poemdexter** [comment] 2017-10-04 19:15
@mspiegel Current state, all actors have ability to turn on/off lgtm as well as github protected branches.  We can reduce the amount of potential malicious actors by restricting who can alter github protected branches.  And that someone should maybe be a single release engineer or someone who isn't contributing directly to the repo.  

In the end, you're still going to need to trust *SOMEONE* with admin access to these tools.  I don't believe anyone can code your way around a people problem.

**Comment by satishc1** [comment] 2017-10-05 11:01
@tabladrum @poemdexter @mspiegel @jdamick Thank you for the inputs and feedback. We will research it further and put in improvements.

**Comment by mspiegel** [comment] 2017-10-11 14:47
I'm going to make an attempt and incorporating the changes above. I'll submit a PR

**Closed** 2017-10-25 19:40 UTC
