### ISSUE TITLE
Jenkins Collector Error

### ISSUE THREAD

**Issue by stangem** [capitalone/Hygieia#2287] opened 2018-06-14 14:40 UTC
Hey!

When I try to use the command   

"java -jar jenkins-build-collector-2.0.5-SNAPSHOT.jar --spring.config.name=jenkins --spring.config.location=~/hygieia-master/collectors/build/jenkins/jenkins.properties"

My API is running, MongoDB is connected and here is my Prop file for Jenkins.
    
       dbname=dashboarddb
       dbhost= localhost
       dbport=27017
       dbreplicaset= false
       dbhostport= localhost:27017
       dbusername= dashboarduser
       dbpassword= dbpassword
       jenkins.cron= 0 0/5 * * * *
       jenkins.pageSize= 1000
       jenkins.folderDepth= 10
       jenkins.servers[0]= https://jenkins.company.com
       jenkins.usernames[0]= username
       jenkins.apiKeys[0]= "ApiKey"
       jenkins.saveLog= true
       jenkins.searchFields[0]= options.jobName
       jenkins.searchFields[1]= niceName

I get this error involving the HudsonCollectorTask.

2018-06-14 10:34:25,929 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hudsonCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
	at com.capitalone.dashboard.Application.main(Application.java:16) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
Caused by: java.lang.NullPointerException: null
	at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:95) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:82) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	... 23 common frames omitted
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hudsonCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101)
	at com.capitalone.dashboard.Application.main(Application.java:16)
	... 6 more
Caused by: java.lang.NullPointerException
	at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265)
	at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:95)
	at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:82)
	at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44)
	at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 23 more

**Comment by subodhbattina** [comment] 2018-06-14 15:23
@stangem: I am seeing this exception below in the log you shared:

Caused by: java.lang.NullPointerException
at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265)

In your properties file, can you please remove the spaces after the "=", and also any white spaces after the the value itself, and give that a shot.

dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
dbusername=dashboarduser
dbpassword=dbpassword
jenkins.cron=0 0/5 * * * *
jenkins.pageSize=1000
jenkins.folderDepth=10
jenkins.servers[0]=https://jenkins.company.com
jenkins.usernames[0]=username
jenkins.apiKeys[0]="ApiKey"
jenkins.saveLog=true
jenkins.searchFields[0]=options.jobName
jenkins.searchFields[1]=niceName

**Comment by stangem** [comment] 2018-06-14 15:34
Okay so I tried that, Still getting the same error. I also tried closing the gaps with the Cron but no change either. Here are my new properties. Thank you for responding, I appreciate the help.

dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
dbusername=dashboarduser
dbpassword=dbpassword
jenkins.cron=0 0/5 * * * *
jenkins.pageSize=1000
jenkins.folderDepth=10
jenkins.servers[0]=https://jenkins.company.com
jenkins.usernames[0]=username
jenkins.apiKeys[0]="ApiKey"
jenkins.saveLog=true
jenkins.searchFields[0]=options.jobName
jenkins.searchFields[1]=niceName

**Comment by subodhbattina** [comment] 2018-06-15 15:30
@stangem , Sure, I hope we are able to solve your issue here.

More specifically, the error seems to be coming from this method below in the class CollectorTask
"at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73)"

@PostConstruct
    public void onStartup() {
        taskScheduler.schedule(this, new CronTrigger(getCron()));
        setOnline(true);
    }

I am not sure what IDE you are using, are you able to go into the debug mode and see what "getCron()" is returning?

**Comment by matthewbeasley** [comment] 2018-06-19 14:57
@stangem - this seems to be caused by `--spring.config.location=~/hygieia-master/collectors/build/jenkins/jenkins.properties`. Specifically `~`. Please use an absolute path to your properties file.

**Comment by stangem** [comment] 2018-06-19 17:48
@matthewbeasley @subodhbattina 
Okay I will try using an Absolute path and will also try to see what what "getCron" is returning.

**Comment by subodhbattina** [comment] 2018-06-26 15:14
@stangem: Since we didn't hear back from you, assuming this issue is resolved at your end, and hence closing it. Thanks

**Closed by subodhbattina** 2018-06-26 15:14 UTC

**Comment by stangem** [comment] 2018-06-27 14:35
@subodhbattina @matthewbeasley 

Hi, I apologize for the wait. I tried using an absolute path, Here is what I used
 
"java -jar jenkins-build-collector-2.0.5-SNAPSHOT.jar --spring.config.name=jenkins --spring.config.location=C:\Hygieia-master\collectors\build\jenkins\jenkins.properties"

Also tried
"java -jar jenkins-build-collector-2.0.5-SNAPSHOT.jar --spring.config.name=jenkins --spring.config.location=D:\Hygieia-master\collectors\build\jenkins\jenkins.properties"


What I'm noticing is that I'm getting the same issue with most of my Collectors that I try to run. I tried running my Gitlab collector and I get the same issue.

**Comment by rvema** [comment] 2018-06-27 14:46
@stangem since your OS is windows you need to use ava -jar jenkins-build-collector-2.0.5-SNAPSHOT.jar --spring.config.name=jenkins --spring.config.location=D:/Hygieia-master/collectors/build/jenkins/jenkins.properties

**Comment by stangem** [comment] 2018-06-27 14:50
@rvema  

My OS is Mac, Sorry I should have stated that.

**Comment by rvema** [comment] 2018-06-27 15:23
@stangem What is the location of your properties file on your system?

**Comment by stangem** [comment] 2018-06-27 15:30
@rvema 

the Location is ~/Hygieia-master/collectors/build/jenkins

**Comment by DineshKRD** [comment] 2018-07-31 11:06
Hi all,
      Am also getting the same error and i tried with different collector's too.

Below is the error am getting while i execute the command 

java -jar xldeploy-deployment-collector-2.0.5-SNAPSHOT.jar --spring.config.name=xldeploy --spring.config.location=D:\Hygieia-master\collectors\deploy\xldeploy\xldeploy.properties


2018-07-31 05:49:12,828 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'XLDeployCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at com.capitalone.dashboard.Application.main(Application.java:13) [xldeploy-deployment-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_151]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [xldeploy-deployment-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
Caused by: java.lang.NullPointerException: null
        at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:95) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:82) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_151]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        ... 23 common frames omitted
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'XLDeployCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101)
        at com.capitalone.dashboard.Application.main(Application.java:13)
        ... 6 more
Caused by: java.lang.NullPointerException
        at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265)
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:95)
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:82)
        at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44)
        at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
        ... 23 more

**Comment by MousomGITHub** [comment] 2018-10-15 06:18
hey, i am in process of setting up the Hygieia dashboard and collectors.
i can get these working -
however i am not able to see any thing on the dashboard from collectors...

http://...:8080/api/dashboard - returning empty - []
i can see in the jenkins collector logs (in debug mode) - the jobs names and etc, however i am not able to understand why these are not showing up in the dashboard.
2018-10-15 17:15:03,509 DEBUG c.c.d.collector.DefaultHudsonClient - buildNumber: 3
2018-10-15 17:15:03,509 DEBUG c.c.d.collector.DefaultHudsonClient - Adding Build: http:///job/wrapper_deploy_docker_st/3/
2018-10-15 17:15:03,509 DEBUG c.c.d.collector.DefaultHudsonClient - buildNumber: 2
2018-10-15 17:15:03,509 DEBUG c.c.d.collector.DefaultHudsonClient - Adding Build: http:///job/wrapper_deploy_docker_st/2/
2018-10-15 17:15:03,509 DEBUG c.c.d.collector.DefaultHudsonClient - buildNumber: 1
2018-10-15 17:15:03,509 DEBUG c.c.d.collector.DefaultHudsonClient - Adding Build: http:///job/wrapper_deploy_docker_st/1/
2018-10-15 17:15:03,509 INFO c.c.d.collector.CollectorTask - Fetched jobs 3s
2018-10-15 17:15:03,552 INFO c.c.d.collector.CollectorTask - New jobs 0 0s
2018-10-15 17:15:03,555 INFO c.c.d.collector.CollectorTask - New builds 0 0s
2018-10-15 17:15:03,558 INFO c.c.d.collector.CollectorTask - New configs 0 0s
2018-10-15 17:15:03,558 INFO c.c.d.collector.CollectorTask - Finished 3s

Please note that i have not set up any ldap authentication, i am using standard authentication post sign up.

sonar collector issue:
018-10-15 17:15:00,252 WARN o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: AWSALB=MLAAhi0tymi5qD+JZmgWXZCasXhU0diqdRDgHHcsA2/C38Kxm8EtbklCVXhk8dDrRSPjVrZJxoZDDGbj1nNK3DAC86FVaCWdKrXT1iTaEmDrjzkAJYe3psBQQstE; Expires=Mon, 22 Oct 2018 06:15:00 GMT; Path=/". Invalid 'expires' attribute: Mon, 22 Oct 2018 06:15:00 GMT
2018-10-15 17:15:00,252 ERROR c.c.d.collector.DefaultSonar6Client - org.springframework.web.client.HttpClientErrorException: 404
2018-10-15 17:15:00,252 INFO c.c.d.collector.CollectorTask - Fetched projects 0 0s
2018-10-15 17:15:00,252 INFO c.c.d.collector.CollectorTask - New projects 0 0s
2018-10-15 17:15:00,254 INFO c.c.d.collector.CollectorTask - Updated 0 0s

Dashboard -
2018-10-15 16:30:35,878 ERROR c.c.d.rest.RestApiExceptionHandler - An Authentication object was not found in the SecurityContext

Really appreaciate if someone helps here.
