### ISSUE TITLE
sonar collector is collecting data but not displaying data on dashboard

### ISSUE THREAD

**Issue by meet101** [capitalone/Hygieia#1415] opened 2017-05-23 18:58 UTC
Hi,
I just got hygieia up and running on Linux box. I tried to setup two collector Jenkins and Sonar. Both looks running fine and collecting data. On dashboard when i tried to setup only Jenkins is displaying data. Sonar is not showing any data. what can be reason? I want to make it work. please help me to get it up and running. 

here is the output from sonar collector:
2017-05-23 18:45:00,013 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-05-23 18:45:00,013 INFO  c.c.d.collector.CollectorTask - http://sonartestserver.corppvt.com:9000/
2017-05-23 18:45:00,013 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-05-23 18:45:00,115 INFO  c.c.d.collector.CollectorTask - Fetched projects   37            0s
2017-05-23 18:45:00,115 INFO  c.c.d.collector.CollectorTask - New projects            0        0s
2017-05-23 18:45:00,219 INFO  c.c.d.collector.CollectorTask - Updated                 1        0s
2017-05-23 18:45:00,220 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2017-05-23 18:50:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar
2017-05-23 18:50:00,023 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-05-23 18:50:00,023 INFO  c.c.d.collector.CollectorTask - http://sonartestserver.corppvt.com:9000/
2017-05-23 18:50:00,023 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-05-23 18:50:00,124 INFO  c.c.d.collector.CollectorTask - Fetched projects   37            0s
2017-05-23 18:50:00,125 INFO  c.c.d.collector.CollectorTask - New projects            0        0s
2017-05-23 18:50:00,223 INFO  c.c.d.collector.CollectorTask - Updated                 0        0s
2017-05-23 18:50:00,224 INFO  c.c.d.collector.CollectorTask - Finished                         0s

![sonarissue](https://cloud.githubusercontent.com/assets/17306302/26370964/56a0a0d2-3fc7-11e7-9f6f-5d750e3376c0.png)

Also, I have a question regarding other collector, 
can we use code commit instead of Github collector without making any change in collector? if not, how hard is to make a collector? for source repo we are using Code commit (can move to Bit bucket, so it's already supported by Hygieia) but for Deployment we are using AWS Elastic beanstalk/codepipeline (I want to make collector for it, Any suggestion?) 

hopefully I will get this tool up and running, Great tool. so excited to get this setup in our environment.

Any help would be appreciated! Thank you

**Comment by nireeshT** [comment] 2017-05-23 19:06
@meet101  - do you see any error in browser console.

**Comment by meet101** [comment] 2017-05-23 19:33
@nireeshT - No, I don't see any error in browser console, When i click on configure button, It's giving me the list of project from sonar. It's fetching all available project from sonar. Other two options are not open to select as per screenshot
![image](https://cloud.githubusercontent.com/assets/17306302/26372643/9c4cf338-3fcc-11e7-9fc7-468661f888c0.png)

Also, here is my application.properties
-------------------------------------
# Database Name
dbname=dashboard

# Database HostName - default is localhost
dbhost=127.0.0.1

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=admin

# Database Password - default is blank
dbpassword=admin

# Collector schedule (required)
sonar.cron=0 0/5 * * * *

# Sonar server(s) (required) - Can provide multiple
sonar.servers[0]=http://sonartestserver.corppvt.com:9000/
# Sonar version, match array index to the server. If not set, will default to version prior to 6.
sonar.versions[0]=5.6
# Sonar Metrics - Required.
#Sonar versions lesser than 5.4
#sonar.metrics[0]=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,violations_density,sqale_index,test_success_density,test_failures,test_errors,tests
#for Sonar 5.4 and above
sonar.metrics[0]=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,violations_density,sqale_index,test_success_density,test_failures,test_errors,tests

----------------------
I am using sonar 5.6 version. Do i need to change sonar.metrics specific to my sonar setup or it should work with default?

**Comment by poloHex** [comment] 2017-05-25 08:25
seems the code doesn't work for sonar version between 5.4 and 6.3. http://sonar_server:9000/api/project_analyses/search?project=com.sap.csc.ems:ems-common:origin/develop:404 Not Found.
the /api/project_analyses only work for 6.3. in previous version should use /api/events. but unfortunately
our sonar version is 6.1. some one working on this?

**Comment by meet101** [comment] 2017-05-25 14:31
@poloHex - If i upgrade sonar server to 6.3, Will it work? is it tested on 6.3?
Thanks,

**Comment by Sbrenthughes** [comment] 2017-05-25 15:04
@poloHex can you update to the latest code? A fix was pushed yesterday for the issue you are seeing. The issue was resolved in https://github.com/capitalone/Hygieia/pull/1413

Please reopen if the issue is not resolved for you.

**Closed by Sbrenthughes** 2017-05-25 15:04 UTC

**Comment by willuk2010** [comment] 2017-06-12 11:12
@poloHex im using sonar 6.2, and seeing the error with the latest code,

2017-06-12 11:09:00,165 ERROR c.c.d.collector.DefaultSonar6Client - Rest Client Exception: http://sonarqube-connect-dev.appls.cap1.paas.xxxxxxxxxx.corp/api/project_analyses/search?project=com.xxxxxxxxx:customers-api:404 Not Found

Do i need to have anything specific in my properties ? this is all i have.

#Database Name
dbname=dashboard

#Database HostName - default is localhost
dbhost=hygieia-mongodb

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=db

#Database Password - default is blank
dbpassword=dbpass

#Collector schedule (required)
sonar.cron=0 * * * * *

sonar.servers[0]=http://sonarqube-connect-dev.appls.cap1.paas.xxxxxxxxxx.corp
sonar.versions[0]=6.2

#Sonar Authentication Username - default is blank
sonar.username=admin

#Sonar Authentication Password - default is blank
sonar.password=xxxxxxxxxx

#Sonar Metrics
sonar.metrics=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,violations_density,sqale_index,test_success_density,test_failures,test_errors,tests

**Comment by senapatirupen** [comment] 2018-02-20 14:38
does it support sonar 6.4 version, i am not getting any output on dashboard
