### ISSUE TITLE
Jira widget shows me all 0's

### ISSUE THREAD

**Issue by vishnuvangala** [capitalone/Hygieia#1029] opened 2016-12-12 13:39 UTC
Team,
Can someone please help me with configuring Jira dashboard. Looks like Im able to see my project details, and other stuff while configuring widget, but I'm seeing all 0's (Open: 0, WIP: 0, Done: 0).. I see some exceptions in console.. please find the below.

Console output
----------------------
```
2016-12-12 18:41:46,096 INFO  com.capitalone.dashboard.Application - Started Application in 13.629 seconds (JVM running for 16.009)
2016-12-12 18:42:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-12-12 18:42:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-12-12 18:42:00,009 INFO  c.c.d.collector.CollectorTask - https://Mycompany.atlassian.net/
2016-12-12 18:42:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-12-12 18:42:07,534 INFO  c.c.d.collector.CollectorTask - Team Data               3        7s
2016-12-12 18:42:08,405 INFO  c.c.d.collector.CollectorTask - Project Data            3        0s
2016-12-12 18:43:03,610 ERROR o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-1 [CLOSED] HTTP protocol exception: null
java.nio.channels.ClosedChannelException: null
        at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257) ~[na:1.8.0_111]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300) ~[na:1.8.0_111]
        at org.apache.http.nio.reactor.ssl.SSLIOSession.receiveEncryptedData(SSLIOSession.java:340) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:366) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:118) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:220) [httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:284) [httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106) [httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:604) [httpcore-nio-4.2.2.jar!/:4.2.2]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2016-12-12 18:43:03,611 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.RuntimeException: java.net.SocketTimeoutException
        at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-14.0.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.apply(DefaultHttpClient.java:256) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.apply(DefaultHttpClient.java:249) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:276) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
        at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:272) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
        at com.atlassian.util.concurrent.Promises$2.onFailure(Promises.java:167) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1145) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:68) ~[guava-14.0.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1$2.run(SettableFuturePromiseHttpPromiseAsyncClient.java:59) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable$1.run(SettableFuturePromiseHttpPromiseAsyncClient.java:197) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:90) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:192) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.net.SocketTimeoutException: null
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:279) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.client.LoggingAsyncRequestExecutor.timeout(LoggingAsyncRequestExecutor.java:128) ~[httpasyncclient-4.0-beta3-atlassian-1.jar!/:4.0-beta3-atlassian-1]
        at org.apache.http.impl.nio.DefaultHttpClientIODispatch.onTimeout(DefaultHttpClientIODispatch.java:136) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.DefaultHttpClientIODispatch.onTimeout(DefaultHttpClientIODispatch.java:50) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:169) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:257) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:494) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:207) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:284) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:604) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        ... 1 common frames omitted
2016-12-12 18:43:03,613 ERROR o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-1 [CLOSED] HTTP protocol exception: null
java.nio.channels.ClosedChannelException: null
```
![image](https://cloud.githubusercontent.com/assets/24268077/21101291/79087b16-c09e-11e6-9b7c-d61f2046e4fd.png)

**Comment by MarkRx** [comment] 2016-12-12 13:49
Please add these properties to debug and attach the debug output: 

- logging.level.com.capitalone.dashboard=DEBUG
- logging.level.com.capitalone.dashboard.collector=DEBUG
- logging.level.com.atlassian.jira=INFO

What java version? Jira version? Did this happen before the recent jira changes?

@pxk5958

**Comment by vishnuvangala** [comment] 2016-12-14 12:30
Hi,
added logging level properties and surprisingly I don't see any errors after my restart.. But still I'm seeing all 0's in open,WIP,Done.. when I verified in "feature" table of mongo db.. I can see all the stories/issues with "open, InProgress & done" state. For every refresh I can see some issues in progress.. but the count always remains the same to 0.  Not sure what else I'm missing here..

**"What java version? Jira version? Did this happen before the recent jira changes?"**
--> My Java version is **openjdk version "1.8.0_111"**
--> Jira version is **JIRA v1000.621.2**
--> This is first time I have started my Jira collector. (Infact even Im new to HYGIEIA).

Here is the log after updating above properties.
------------------------------------------------------------------------
2016-12-14 16:05:21,609 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: XXXX
2016-12-14 16:05:21,609 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:17}] to 192.168.XXX.XX:27017
2016-12-14 16:05:21,611 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=192.168.XXX.XXX:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 14]}, minWireVersion=0, maxWireVersion=3, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=981769}
2016-12-14 16:05:21,618 INFO  org.mongodb.driver.cluster - Cluster created witings {hosts=[192.168.XXX.XX:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2016-12-14 16:05:21,628 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@987df09e, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@4963f030, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@7b17aaeb, socketFactory=javax.net.DefaultSocketFactory@826ca40, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2016-12-14 16:05:21,681 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:18}] to 192.168.XXX.XXX:27017
2016-12-14 16:05:21,683 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=192.166.XXX.XXX:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 14]}, minWireVersion=0, maxWireVersion=3, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=1117496}
2016-12-14 16:05:23,047 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2016-12-14 16:05:23,047 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: 192.168.XXX.XXX:27017
2016-12-14 16:05:23,048 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[192.168.XXX.XXX:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2016-12-14 16:05:23,052 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@987df09e, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@4963f030, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@7b17aaeb, socketFactory=javax.net.DefaultSocketFactory@826ca40, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2016-12-14 16:05:23,118 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:19}] to 192.168.XXX.XXX:27017
2016-12-14 16:05:23,120 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=192.168.XXX.XXX:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 14]}, minWireVersion=0, maxWireVersion=3, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=992351}
2016-12-14 16:05:24,619 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2016-12-14 16:05:24,640 INFO  com.capitalone.dashboard.Application - Started Application in 14.604 seconds (JVM running for 16.802)
2016-12-14 16:06:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-12-14 16:06:00,018 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-12-14 16:06:00,019 INFO  c.c.d.collector.CollectorTask - https://mycompany.atlassian.net/
2016-12-14 16:06:00,019 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-12-14 16:06:00,024 DEBUG c.c.d.client.team.TeamDataClientImpl - Constructing data collection for the feature widget, team-level data...
2016-12-14 16:06:04,333 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 3
2016-12-14 16:06:04,472 INFO  c.c.d.collector.CollectorTask - Team Data               3        4s
2016-12-14 16:06:04,476 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2016-12-14 16:06:05,136 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 3
2016-12-14 16:06:05,180 INFO  c.c.d.collector.CollectorTask - Project Data            3        0s
2016-12-14 16:06:05,188 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
2016-12-14 16:06:05,965 DEBUG c.c.d.c.story.StoryDataClientImpl - Obtaining story information starting at index 0...
2016-12-14 16:06:07,015 DEBUG c.c.d.client.DefaultJiraClient - Processing issues 0 - 0 out of 0

![image](https://cloud.githubusercontent.com/assets/24268077/21181975/964d2c60-c226-11e6-9a10-ce081ef97860.png)

**Comment by MarkRx** [comment] 2016-12-14 13:37
I'm not sure what jira v1000.621.2 is. It should be something like 5.x, 6.x, or 7.x.

To get estimates to show up your jira must be configured to have estimates on story points. There is no count of the number of issues currently - #940

You also need to make sure you configured the estimate fields
feature.jiraIssueTypeNames=Story
feature.jiraStoryPointsFieldName=customfield_10002

There are some trouble shooting steps listed in the readme here: https://github.com/capitalone/Hygieia/tree/master/collectors/feature/jira

**Comment by leahxu** [comment] 2016-12-14 19:38
Check what values you have for time/story points estimate. JIRA lets you turn off estimates so it feeds Hygieia nulls for those fields, which then get turned into 0.

**Comment by vishnuvangala** [comment] 2016-12-16 08:48
The below are the properties configured for my JIRA.. Please check once if i'm missing something.

<db properties>
logging.file=./logs/jira.log
feature.pageSize=100
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000
feature.cron=0 * * * * *

feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.jiraBaseUrl=https://MyCompany.atlassian.net/
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=dmlzaG51dmFyZGhhbiXXXXXXGFjaGljb25zdWx0aW5nLmNvbTkaGFuQDEyMw==
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

feature.jiraIssueTypeNames=Story
feature.jiraSprintDataFieldName=customfield_10000
feature.jiraEpicIdFieldName=customfield_10002
feature.jiraStoryPointsFieldName=customfield_10003
feature.jiraTeamFieldName=customfield_10703


One sample record from my mongo DB: (Please check if something I have forgot to fill it in Jira itself?)
-----------------------------------------------------
{
    "_id" : ObjectId("584ea3198ebde6XXX1e70d93"),
    "_class" : "com.capitalone.dashboard.model.Feature",
    "collectorId" : ObjectId("584ea1308ebdXXXcecbcef46"),
    "sId" : "10104",
    "sNumber" : "ABCD-7",
    "sName" : "Implementation of my test feature.",
    "sTypeId" : "10001",
    "sTypeName" : "Story",
    "sStatus" : "Done",
    "sState" : "Done",
    "sEstimate" : "0",
    "sEstimateTime" : 0,
    "sUrl" : "https://myCompany.atlassian.net/browse/ABCD-7",
    "changeDate" : "2016-03-12T01:54:20.0000000",
    "isDeleted" : "False",
    "sOwnersID" : [ 
        "v.vangala"
    ],
    "sOwnersIsDeleted" : [],
    "sOwnersChangeDate" : [],
    "sOwnersState" : [ 
        "Active"
    ],
    "sOwnersUsername" : [ 
        "vvangala"
    ],
    "sOwnersFullName" : [ 
        "vishnu vangala"
    ],
    "sOwnersShortName" : [ 
        "vvangala"
    ],
    "sTeamIsDeleted" : "False",
    "sTeamAssetState" : "",
    "sTeamChangeDate" : "",
    "sSprintIsDeleted" : "False",
    "sSprintChangeDate" : "",
    "sSprintAssetState" : "",
    "sSprintEndDate" : "2016-20-12T01:54:20.0000000",
    "sSprintBeginDate" : "2016-03-12T01:54:20.0000000",
    "sSprintName" : "",
    "sSprintID" : "",
    "sEpicIsDeleted" : "False",
    "sEpicChangeDate" : "",
    "sEpicAssetState" : "",
    "sEpicType" : "",
    "sEpicEndDate" : "",
    "sEpicBeginDate" : "",
    "sEpicName" : "",
    "sEpicNumber" : "",
    "sEpicID" : "",
    "sProjectPath" : "",
    "sProjectIsDeleted" : "False",
    "sProjectState" : "",
    "sProjectChangeDate" : "",
    "sProjectEndDate" : "",
    "sProjectBeginDate" : "",
    "sProjectName" : "My Project",
    "sProjectID" : "10000"
}

**Comment by leahxu** [comment] 2016-12-16 15:38
sEstimate and sEstimateTime are 0, they're populated by story points and time estimates data from JIRA which you likely didn't set. Thus when it aggregates how much time is in each queue it becomes zero. You can confirm by changing the values in your mongodb database to be another number (e.g. 1 and you'll see it reflected on your dashboard)

**Comment by Mahendra1260** [comment] 2016-12-20 18:53
I am seeing the dashboard as below:
![image](https://cloud.githubusercontent.com/assets/3480342/21363644/8a3e5506-c713-11e6-878c-bd6e385da541.png)

Open : 0
WIP:2
Done:0

Although the particular task/story is done.. not sure why it is showing as 0. I have selected 'hours' from the dropdown

**Comment by Mahendra1260** [comment] 2016-12-20 19:12
Also, when I see all the field as 0 if I select ,my project team from the dropdown.
But when i select 'Any' from the dropdown from Team Field.. it starts showing me data as above screenshot

**Comment by pxk5958** [comment] 2016-12-20 19:50
If you select hours, it'll show whatever hours you assigned as estimates to the tasks. Please check how many hours/story points you assigned to the tasks in Jira. 
Regarding your second comment, If you don't select your particular team, it'll aggregate data from other teams in your project, so that's why it shows the points.

**Comment by Mahendra1260** [comment] 2016-12-21 05:52
@pxk5958 For first comment: If I select hours and it will show the estimated hours assigned for the story/task..then what is the significance of having OPEN , and DONE field. Under what circumstance I can see data in those field?

To the second comment: I have only one Team associated with the project which I have mentioned in the application.properties file. On selecting Team from the dropdown, I was expecting it to show the data related to my Team?
When I don't select any team then in that case it shows data, which is slightly misleading to me.

**Comment by vishnuvangala** [comment] 2016-12-21 09:05
@pxk5958 @Mahendra1260 
@leahxu  
After changing the value of sEstimate and sEstimateTime now I'm able to see some numbers over there.. what I understood is.. the widget shows the number of sEstimate hours in "Open"/"WIP", and it shows only when I select KANBAN but not showing in sprint..  
Even though if I select all teams.. the widgets shows me all 0's. Not sure of what exactly it is happening.. but need a clear understanding of this widget..

**Comment by MarkRx** [comment] 2016-12-21 13:26
To show scrum sprints you must (1) have the collector property configured, and (2) have a project/team have an active ending sprint. If a sprint exists but has no end date it will be treated as a kanban sprint.
@vishnuvangala as is the case with most of the jira issues reported here the cause has been the jira collector not being correctly configured. Note that if you make a change to the collector config the change will only apply to newly collected jira items. Hence, you may need to wipe your jira data and recollect it.

sEstimate comes from the story point estimates that are put on stories. sEstimateTime comes from time estimates that are put on subtasks of stories. Hours estimates for tasks keep track of the total estimate and how much time has been put into the issue. From these open, wip, and done values can be deduced.

@Mahendra1260 double check your configuration. Note that if a sprint is not active (start date <= now <=(?) end date) it will not show up. If you do not select any team than "Any team" is assumed.

**Comment by satishc1** [comment] 2017-02-03 15:30
@vishnuvangala The feature widget now has an option to display metrics based on the number of tickets instead of estimates. This is for setups that do not use estimates.
Functionality merged in https://github.com/capitalone/Hygieia/pull/1054 Use latest codebase. You’ll also need to follow cleanup instructions provided in https://github.com/capitalone/Hygieia/pull/1137

**Closed by satishc1** 2017-02-03 15:30 UTC
