### ISSUE TITLE
Issue with VersionOne Ultimate Edition  v.15.2.4.9371

### ISSUE THREAD

**Issue by aniketvsawant** [capitalone/Hygieia#196] opened 2015-12-08 15:56 UTC
Hi, I am facing issue with the current VersionOne collector implementation. Does not work with VersionOne Ultimate Edition  v.15.2.4.9371. VersionOne collector goes on populating data from ALM without any updates. Sprint count goes on increment with big numbers without deleting older data.
Can you please suggest work around it. Thanks.

![capture](https://cloud.githubusercontent.com/assets/3583504/11696015/d3475308-9e77-11e5-8789-64d5998ef7dc.PNG)

**Comment by amp5208** [comment] 2016-03-11 17:43
@aniketvsawant , Thank you for reaching out; sorry I was not able to respond sooner - I just noticed this question.

The VersionOneFeatureCollector and subsequent Hygieia Feature Widget was tested on VersionOne Ultimate Edition.  Do you have 4090 story points currently in the VersionOne out-of-the-box "In Progress" status, or similar?  This collector will retrieve data for your current active sprint and accumulate all story points associated to that active sprint, as updates on the stories occur.  Essentially, this is normal, expected behavior.

Please elaborate if you require more insight.  Otherwise, please let us know if this issue can be closed.

**Comment by tabladrum** [comment] 2016-03-22 00:51
Closing it due to no activities.

**Closed by tabladrum** 2016-03-22 00:51 UTC
