### ISSUE TITLE
AWS Region Issue

### ISSUE THREAD

**Issue by QuantumBitsIT** [capitalone/Hygieia#1860] opened 2017-11-21 21:56 UTC
I have installed Hygieia with AWS plugin and tried different ways to set up AWS through the Profile and EC2 role. It always defaults back to us-east-1 region, I have tried different profiles and regions and created dedicated IAM policies to limit to specific regions and it still goes back to us-east-1 to list EC2 instances. Any solution?

**Comment by yks0000** [comment] 2017-11-26 19:01
I made local changes to Hygieia code to get it going (until it is being fixed) for the region I want to connect. 

Changes that we need to make it  are present in https://github.com/capitalone/Hygieia/issues/1852#issuecomment-347030067

**Comment by matthewbeasley** [comment] 2018-01-11 22:16
@QuantumBitsIT - #1861 is a duplicate of this issue. There's more of a conversation there so I gave a response there. Please check that issue out.

**Closed by matthewbeasley** 2018-01-11 22:16 UTC
